name: build

on:
  push:

  workflow_dispatch:

jobs:
  build_win:
    runs-on: windows-2022
    env:
      BOOST_VER_DOT: 1.78.0
      BOOST_VER_UND: 1_78_0

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Download boost
        shell: bash
        run: curl -L -O https://boostorg.jfrog.io/artifactory/main/release/${{ env.BOOST_VER_DOT }}/source/boost_${{ env.BOOST_VER_UND }}.zip

      - name: Extract boost
        run: 7z x boost_${{ env.BOOST_VER_UND }}.zip

      - name: Show files
        shell: bash
        run: ls


